version: 1
labels:
  - label: "TestLabel"
    title: ".*"
  - label: "TestFileMatch"
    files:
      - "cmd/.*.go"
      - "pkg/.*.go"
      - "build.sbt"
  - label: "steward"
    authors: ["softwaremill-ci"]
  - label: "S"
    size:
      below: 100