name: FOO
on:
  workflow_dispatch:
  pull_request:
    branches: ['**']
  push:
    branches: ['**']
    tags: [v*]
jobs:
  logFoo:
    name: LogFOO
    runs-on: ubuntu-latest
    steps:
      - name: Logging context
        run: |
          echo "------- [FOO] -------- user: ${{github.event.pull_request.user.login }}, event name: ${{ github.event_name }}, conc = ${{ github.event.workflow_run.conclusion }}."

  barFoo:
    name: BarFoo
    needs: logFoo
    uses: ./.github/workflows/bar.yml